var audios = {
    '人名': [
        {
            "name":"恭迎丘公建祥",
            "url":"/media/sounds/.mp3_Qvemr4N"
         },
         {
            "name":"哈鮭企鵝",
            "url":"/media/sounds/.mp3_7OLKGGO"
         },
         {
            "name":"嘎抓",
            "url":"/media/sounds/.mp3_R1pRA1t"
         },
         {
            "name":"兆元",
            "url":"/media/sounds/.mp3_zPEz9c6"
         },
         {
            "name":"小胖",
            "url":"/media/sounds/.mp3_QpwQt86"
         },
         {
            "name":"小胖2",
            "url":"/media/sounds/2_T68S1ZA.mp3"
         },
         {
            "name":"顯考丘公建祥",
            "url":"/media/sounds/.mp3_bJkmTFN"
         },
         {
            "name":"張兆元",
            "url":"/media/sounds/.mp3_XeWcKbg"
         },
         {
            "name":"邱少爺",
            "url":"/media/sounds/.mp3_ofbqNBN"
         },
         {
            "name":"顯考王公銘森哈鮭企鵝",
            "url":"/media/sounds/.mp3_amfgyo4"
         },
         {
            "name":"卓孝宣",
            "url":"/media/sounds/.mp3_qd0uQQo"
         },
    ],
    '升旗': [
        {
            "name":"主席",
            "url":"/media/sounds/.mp3_18G5w9A"
         },
         {
            "name":"下去啦～",
            "url":"/media/sounds/.mp3_DFdXjEP"
         },
         {
            "name":"哎呦～",
            "url":"/media/sounds/.mp3_QrtcPwQ"
         },
         {
            "name":"這就是我們的",
            "url":"/media/sounds/.mp3_8ymyDyI"
         },
         {
            "name":"即將啟航的時刻",
            "url":"/media/sounds/.mp3_HUEwc5Z"
         },
         {
            "name":"同志們",
            "url":"/media/sounds/.mp3_M7kUwsA"
         },
         {
            "name":"我們即將舉行升旗典禮",
            "url":"/media/sounds/.mp3_tUe2ygG"
         },
         {
            "name":"一柱清香",
            "url":"/media/sounds/.mp3_gxhPQkx"
         },
         {
            "name":"再上香",
            "url":"/media/sounds/.mp3_8RMm9J9"
         },
         {
            "name":"獻花獻果",
            "url":"/media/sounds/.mp3_zUXmqns"
         },
         {
            "name":"三柱清香罐頭塔我們送上去",
            "url":"/media/sounds/.mp3_BFReUrw"
         },
         {
            "name":"即將飛升為天",
            "url":"/media/sounds/.mp3_bVpSYKX"
         },
         {
            "name":"同志們請起立",
            "url":"/media/sounds/.mp3_ZSJifyG"
         },
         {
            "name":"在鞠躬的同時請脫帽",
            "url":"/media/sounds/.mp3_HfnwSCR"
         },
         {
            "name":"一鞠躬",
            "url":"/media/sounds/.mp3_VtDHyaY"
         },
         {
            "name":"再鞠躬",
            "url":"/media/sounds/.mp3_mbfQGeA"
         },
         {
            "name":"三鞠躬",
            "url":"/media/sounds/.mp3_Wcx0qm3"
         },
         {
            "name":"來賓與家屬打理",
            "url":"/media/sounds/.mp3_g2pyzTf"
         },
    ],
    '罵人': [
        {
            "name":"屌你老母",
            "url":"/media/sounds/.mp3_MGgvnBc"
         },
         {
            "name":"看你娘",
            "url":"/media/sounds/.mp3_8dRNI8f"
         },
         {
            "name":"甲洨喔～",
            "url":"/media/sounds/.mp3_sezrMNa"
         },
         {
            "name":"靠杯喔",
            "url":"/media/sounds/.mp3_KE0u1go"
         },
         {
            "name":"欠我幹啊？是不是？",
            "url":"/media/sounds/.mp3_iCm5mfD"
         },
         {
            "name":"幹死他！",
            "url":"/media/sounds/.mp3_V90v3Uz"
         },
         {
            "name":"他死定了他",
            "url":"/media/sounds/.mp3_NNeVbQx"
         },
         {
            "name":"王八蛋",
            "url":"/media/sounds/.mp3_u5GyBfE"
         },
         {
            "name":"揍死你",
            "url":"/media/sounds/.mp3_eeRpk5h"
         },
         {
            "name":"你倒大楣了",
            "url":"/media/sounds/.mp3_k42Ebs9"
         },
         {
            "name":"你怎麼不下去啊？",
            "url":"/media/sounds/.mp3_ymzeXkq"
         },
         {
            "name":"你倒霉了",
            "url":"/media/sounds/.mp3_i7hzaxU"
         },
         {
            "name":"我沒有去幹他，我他媽不姓張！",
            "url":"/media/sounds/.mp3_EMspCZe"
         },
         {
            "name":"幹你娘G8",
            "url":"/media/sounds/g8.mp3"
         },
         {
            "name":"你有膽別跑幹你娘",
            "url":"/media/sounds/.mp3_Fr0dhay"
         },
         {
            "name":"操你媽啦",
            "url":"/media/sounds/.mp3_Q59LwK6"
         },
         {
            "name":"智障",
            "url":"/media/sounds/.mp3_GVdHujG"
         },
         {
            "name":"大濕：NMSL",
            "url":"/media/sounds/nmsl.mp3"
         },
         {
            "name":"操你媽你叫誰啊",
            "url":"/media/sounds/.mp3_k7tgJCg"
         },
    ],
    '叫聲': [
        {
            "name":"兆元高潮",
            "url":"/media/sounds/mp3cut_J0M19Kg.mp3"
         },
         {
            "name":"兆元高潮2",
            "url":"/media/sounds/.mp3_t3U7oFv"
         },
         {
            "name":"啊啊",
            "url":"/media/sounds/at88-cm-626466910-online-audio-converter-mp3cut.mp3"
         },
         {
            "name":"大濕嗩吶",
            "url":"/media/sounds/.mp3_pybTdjJ"
         },
         {
            "name":"汪",
            "url":"/media/sounds/.mp3_EBZyT3o"
         },
         {
            "name":"啊➚啊➚啊➚",
            "url":"/media/sounds/.mp3_kk0OzW9"
         },
         {
            "name":"埃～",
            "url":"/media/sounds/.mp3_f0EkltN"
         },
         {
            "name":"啵",
            "url":"/media/sounds/.mp3_MCgCt03"
         },
         {
            "name":"兆元的不明叫聲",
            "url":"/media/sounds/.mp3_bZZt709"
         },
         {
            "name":"兆元的不明叫聲2",
            "url":"/media/sounds/2_9UROs2b.mp3"
         },
         {
            "name":"啊～～～",
            "url":"/media/sounds/3_3aTyHtk.mp3"
         },
         {
            "name":"哇～",
            "url":"/media/sounds/.mp3_r3mRO9r"
         },
         {
            "name":"哇～～～",
            "url":"/media/sounds/.mp3_doUTf46"
         },
         {
            "name":"噢～～～",
            "url":"/media/sounds/.mp3_Yp43o6F"
         },
         {
            "name":"诶嘿～",
            "url":"/media/sounds/.mp3_LnaCDvj"
         }
    ],
    '哭': [
        {
           "name":"元元子哭哭",
           "url":"/media/sounds/.mp3_vJDMfn5"
        },
        {
           "name":"元元子哭哭２",
           "url":"/media/sounds/2_qVIr1cb.mp3"
        },
        {
           "name":"嗚嗚嗚嗚嗚",
           "url":"/media/sounds/.mp3_62LU6K6"
        },
    ],
    '小安': [
        {
           "name":"大家好，我是小安",
           "url":"/media/sounds/.mp3_cGYB7q3"
        },
        {
           "name":"我喜歡拉小提琴跳舞還有唱歌",
           "url":"/media/sounds/.mp3_0pHzSH8"
        },
        {
           "name":"如果喜歡歡迎來我的頻道",
           "url":"/media/sounds/.mp3_BbdP5Vn"
        },
    ],
    '甲': [
        {
           "name":"幫他吸",
           "url":"/media/sounds/.mp3_XPMZXvO"
        },
        {
           "name":"蛤？乖乖站好啊！",
           "url":"/media/sounds/.mp3_6UcD4DW"
        },
        {
           "name":"又爽又舒服",
           "url":"/media/sounds/.mp3_GfRcuqk"
        },
        {
           "name":"衛浴設備",
           "url":"/media/sounds/.mp3_AQvH48g"
        },
        {
           "name":"只能在廁所",
           "url":"/media/sounds/.mp3_A4JmahD"
        },
        {
           "name":"馬桶",
           "url":"/media/sounds/.mp3_x7WYWqD"
        },
        {
           "name":"便器",
           "url":"/media/sounds/.mp3_aULw6kz"
        },
        {
           "name":"你們是Gay嗎？",
           "url":"/media/sounds/gay_hZMqOfW.mp3"
        },
        {
           "name":"我的台是Gay台",
           "url":"/media/sounds/gay_pnsVDVF.mp3"
        },
        {
           "name":"屁股人人有份",
           "url":"/media/sounds/.mp3_zcIbDje"
        },
        {
           "name":"禮到人到屁眼也到",
           "url":"/media/sounds/.mp3_JLFfEjh"
        },
        {
           "name":"幹到你屁眼流湯",
           "url":"/media/sounds/.mp3_7YZwjSV"
        },
        {
           "name":"等等來肛吧！",
           "url":"/media/sounds/.mp3_xgnrGrJ"
        },
        {
           "name":"屁眼故障來找我",
           "url":"/media/sounds/.mp3_MGfOnQ8"
        },
        {
           "name":"又粗又大又壯",
           "url":"/media/sounds/.mp3_pJiizp4"
        },
        {
           "name":"GayBar最佳員工",
           "url":"/media/sounds/gay-bar-mp3cut.mp3"
        },
        {
           "name":"正義比我大",
           "url":"/media/sounds/dfpid-lteg0-mp3cut.mp3"
        },
        {
           "name":"現在跟我已經特殊性關西了啦",
           "url":"/media/sounds/.mp3_m8XKsXq"
        },
        {
            "name":"你來當我男朋友好不好？",
            "url":"/media/sounds/.mp3_o0zKQGG"
        },
    ],
    '其他': [
        {
            "name":"兆元你跪啊",
            "url":"/media/sounds/r_qgSILAC.mp3"
         },
         {
            "name":"我長得像盤子嗎",
            "url":"/media/sounds/mp3cut_GOBcLPW.mp3"
         },
         {
            "name":"等你發現",
            "url":"/media/sounds/video-16109063368958.mp3"
         },
         {
            "name":"更好用",
            "url":"/media/sounds/vid16109065234758.mp3"
         },
         {
            "name":"男的幹",
            "url":"/media/sounds/nxx4t-vgzoo-mp3cut.mp3"
         },
         {
            "name":"好牛逼",
            "url":"/media/sounds/-firefox-nightly-2021-01-03-23-22-20-online-audio-converter-mp3cut.mp3"
         },
         {
            "name":"這...這什麼啊？",
            "url":"/media/sounds/.mp3_pwhUoDX"
         },
         {
            "name":"安安啊",
            "url":"/media/sounds/.mp3_Eiqk86r"
         },
         {
            "name":"來來來來來",
            "url":"/media/sounds/.mp3_xycGHnl"
         },
         {
            "name":"讓我看看",
            "url":"/media/sounds/.mp3_6Lqc3Qq"
         },
         {
            "name":"這真的可以做嗎？",
            "url":"/media/sounds/.mp3_4cS8Sjt"
         },
         {
            "name":"可以拉！沒問題啦！",
            "url":"/media/sounds/.mp3_J2YmRnC"
         },
         {
            "name":"や...やります！",
            "url":"/media/sounds/.mp3_QvZxuRG"
         },
         {
            "name":"這個房間",
            "url":"/media/sounds/.mp3_rwLYEP1"
         },
         {
            "name":"把門推開",
            "url":"/media/sounds/.mp3_H7oPwCo"
         },
         {
            "name":"亮亮的",
            "url":"/media/sounds/.mp3_QqnYLgm"
         },
         {
            "name":"真的要做嗎？",
            "url":"/media/sounds/.mp3_ZnEfHCY"
         },
         {
            "name":"你就做嘛！",
            "url":"/media/sounds/.mp3_j0R7stG"
         },
         {
            "name":"我回來啦！",
            "url":"/media/sounds/.mp3_wv5adop"
         },
         {
            "name":"到底是誰啦！",
            "url":"/media/sounds/.mp3_SNombcN"
         },
         {
            "name":"奇奇怪怪的",
            "url":"/media/sounds/id.mp3"
         },
         {
            "name":"變成大濕的形狀",
            "url":"/media/sounds/.mp3_GQGZwUg"
         },
         {
            "name":"大大的",
            "url":"/media/sounds/.mp3_7iiP4Lt"
         },
         {
            "name":"按個讚",
            "url":"/media/sounds/.mp3_YMbw2s3"
         },
         {
            "name":"好可愛",
            "url":"/media/sounds/.mp3_0G9BCcf"
         },
         {
            "name":"好可愛喔～",
            "url":"/media/sounds/.mp3_FyLcYAA"
         },
         {
            "name":"車車",
            "url":"/media/sounds/.mp3_kKb2hld"
         },
         {
            "name":"戴綠帽",
            "url":"/media/sounds/.mp3_Yp1yG0w"
         },
         {
            "name":"不要幫我上香好嗎",
            "url":"/media/sounds/.mp3_nHwnfUq"
         },
         {
            "name":"PEKO",
            "url":"/media/sounds/peko_xlI32l1.mp3"
         },
         {
            "name":"我不知道",
            "url":"/media/sounds/.mp3_RARH3jm"
         },
         {
            "name":"那是什麼？",
            "url":"/media/sounds/.mp3_INOHvjM"
         },
         {
            "name":"我都不看這些的！",
            "url":"/media/sounds/.mp3_ghqhh7X"
         },
         {
            "name":"你餓了嗎？",
            "url":"/media/sounds/.mp3_V21onQI"
         },
         {
            "name":"給你吃點好吃的呦～",
            "url":"/media/sounds/.mp3_jgiFfID"
         },
         {
            "name":"什...什麼好吃的啊？",
            "url":"/media/sounds/.mp3_KPnGSI6"
         },
         {
            "name":"來啦！",
            "url":"/media/sounds/.mp3_EnLFMnS"
         },
         {
            "name":"拿...拿都拿！",
            "url":"/media/sounds/.mp3_SaVFyQg"
         },
         {
            "name":"元元要上車嗎？",
            "url":"/media/sounds/.mp3_OU5n2sn"
         },
         {
            "name":"不要了不要了不好意思不要了",
            "url":"/media/sounds/.mp3_n1abJfx"
         },
         {
            "name":"怕～",
            "url":"/media/sounds/.mp3_vv9syGt"
         },
         {
            "name":"獅子頭",
            "url":"/media/sounds/.mp3_8fd17HU"
         },
         {
            "name":"不要吵啊",
            "url":"/media/sounds/.mp3_p4StLDQ"
         },
         {
            "name":"等一下看了我就下去了",
            "url":"/media/sounds/.mp3_6ORMLw3"
         },
         {
            "name":"他在盯著我",
            "url":"/media/sounds/.mp3_GAXIdak"
         },
         {
            "name":"沒事沒事",
            "url":"/media/sounds/.mp3_dAnfP2k"
         },
         {
            "name":"我愛你",
            "url":"/media/sounds/.mp3_tD9ZK1A"
         },
         {
            "name":"咳瘦",
            "url":"/media/sounds/.mp3_bq1VpCh"
         },
         {
            "name":"是中邪了嗎？",
            "url":"/media/sounds/.mp3_ayGRwhA"
         },
         {
            "name":"是生病了",
            "url":"/media/sounds/.mp3_kFELYPV"
         },
         {
            "name":"變態",
            "url":"/media/sounds/.mp3_KFKQRfx"
         },
         {
            "name":"喂！",
            "url":"/media/sounds/.mp3_3KObnZ5"
         },
         {
            "name":"騎這麼快啊！",
            "url":"/media/sounds/.mp3_ci6BQit"
         },
         {
            "name":"被拖下去",
            "url":"/media/sounds/.mp3_XKnCheF"
         },
         {
            "name":"下車！",
            "url":"/media/sounds/.mp3_6XPkhEo"
         },
         {
            "name":"我愛的是皮卡屁",
            "url":"/media/sounds/.mp3_dHKsEEW"
         },
         {
            "name":"幹有這麼誇張的喔？",
            "url":"/media/sounds/.mp3_KE7boCw"
         },
         {
            "name":"哇幹！",
            "url":"/media/sounds/.mp3_rNYrWjw"
         },
         {
            "name":"太大了",
            "url":"/media/sounds/.mp3_PFCfAH7"
         },
         {
            "name":"真的要娶她了",
            "url":"/media/sounds/.mp3_mFo2yIu"
         },
         {
            "name":"好啦！",
            "url":"/media/sounds/.mp3_8twO2e8"
         },
         {
            "name":"決定了！",
            "url":"/media/sounds/.mp3_ziWarO0"
         },
         {
            "name":"辦婚禮了！",
            "url":"/media/sounds/.mp3_EwlEmLo"
         },
         {
            "name":"等著收我喜帖吧！",
            "url":"/media/sounds/.mp3_zGLOhn2"
         },
         {
            "name":"進入",
            "url":"/media/sounds/.mp3_UvcrPxx"
         },
         {
            "name":"鬼故事",
            "url":"/media/sounds/.mp3_cNcJ0vj"
         },
         {
            "name":"馬老爺",
            "url":"/media/sounds/.mp3_IWq9iyu"
         },
         {
            "name":"邱建祥",
            "url":"/media/sounds/.mp3_s27gO7E"
         },
         {
            "name":"一見鐘䞍",
            "url":"/media/sounds/.mp3_3iMr8BA"
         },
         {
            "name":"哭啊",
            "url":"/media/sounds/.mp3_0GIqxTc"
         },
         {
            "name":"屁眼",
            "url":"/media/sounds/.mp3_hD5HaDb"
         },
         {
            "name":"打開",
            "url":"/media/sounds/.mp3_RKWPHrR"
         },
         {
            "name":"為什麼是我的照片啊？",
            "url":"/media/sounds/.mp3_5zM5Wb0"
         },
         {
            "name":"你是我的屁眼～",
            "url":"/media/sounds/.mp3_YlLzldc"
         },
         {
            "name":"厚呦又我",
            "url":"/media/sounds/.mp3_2expFUH"
         },
         {
            "name":"我要穿女裝",
            "url":"/media/sounds/.mp3_lus3V2U"
         },
         {
            "name":"衝了啦！",
            "url":"/media/sounds/.mp3_BfkAnRw"
         },
         {
            "name":"等一下",
            "url":"/media/sounds/.mp3_4wuO8Po"
         },
         {
            "name":"我不要！",
            "url":"/media/sounds/.mp3_7CVITIL"
         },
         {
            "name":"我好害怕",
            "url":"/media/sounds/.mp3_soEoCey"
         },
         {
            "name":"你就是我的妖豔賤貨",
            "url":"/media/sounds/.mp3_TKruUWZ"
         },
         {
            "name":"NO~~~",
            "url":"/media/sounds/no_hDCn8Pd.mp3"
         },
         {
            "name":"救我！",
            "url":"/media/sounds/.mp3_FpU85TY"
         },
         {
            "name":"龍潭廁所子",
            "url":"/media/sounds/.mp3_XBxAuQE"
         },
         {
            "name":"いたい いたい",
            "url":"/media/sounds/.mp3_2v23bZN"
         },
         {
            "name":"因該不會上車吧？",
            "url":"/media/sounds/.mp3_gbOQFSy"
         },
         {
            "name":"埃！埃！等一下等一下",
            "url":"/media/sounds/.mp3_DPvR6oE"
         },
         {
            "name":"嚇我一跳",
            "url":"/media/sounds/.mp3_17doqeq"
         },
         {
            "name":"呵呵！肥宅",
            "url":"/media/sounds/.mp3_3q4GehY"
         },
         {
            "name":"這不是我的衣服嗎？",
            "url":"/media/sounds/.mp3_tySaZ0Z"
         },
         {
            "name":"打手槍",
            "url":"/media/sounds/.mp3_zThDx90"
         },
         {
            "name":"我好變那個肥宅",
            "url":"/media/sounds/.mp3_rrlF10B"
         },
         {
            "name":"我不想聽拜託不要告述我",
            "url":"/media/sounds/.mp3_vMfjpaV"
         },
         {
            "name":"我看你是很勇喔",
            "url":"/media/sounds/.mp3_AjtIw7J"
         },
         {
            "name":"你這個",
            "url":"/media/sounds/.mp3_v5SOpJW"
         },
         {
            "name":"NTR",
            "url":"/media/sounds/ntr.mp3"
         },
         {
            "name":"睡的真飽",
            "url":"/media/sounds/.mp3_MYL9vjd"
         },
         {
            "name":"怎麼那麼垃圾啊？",
            "url":"/media/sounds/.mp3_R15bTw4"
         },
         {
            "name":"什麼狀況？",
            "url":"/media/sounds/.mp3_n6fcv2s"
         },
         {
            "name":"不對啊",
            "url":"/media/sounds/.mp3_c3lKHdc"
         },
         {
            "name":"我哪是",
            "url":"/media/sounds/.mp3_AGeXdRj"
         },
         {
            "name":"我明明就是",
            "url":"/media/sounds/.mp3_30fUzjw"
         },
         {
            "name":"肥宅",
            "url":"/media/sounds/.mp3_g06gcfv"
         },
         {
            "name":"怎麼有東西黏黏的？",
            "url":"/media/sounds/.mp3_fXLtaS5"
         },
         {
            "name":"好色喔～",
            "url":"/media/sounds/.mp3_sQ6DrCY"
         },
         {
            "name":"気持ちいい～～",
            "url":"/media/sounds/.mp3_Bg92T2V"
         },
         {
            "name":"啊！好香喔～",
            "url":"/media/sounds/.mp3_k9r6Iiu"
         },
         {
            "name":"怎麼那麼臭啊？",
            "url":"/media/sounds/.mp3_Bk1XvKF"
         },
         {
            "name":"我有這麼爛嗎？",
            "url":"/media/sounds/.mp3_EouyLCw"
         },
         {
            "name":"我要放屁了喔！",
            "url":"/media/sounds/.mp3_BodBvvP"
         },
         {
            "name":"盤子們",
            "url":"/media/sounds/.mp3_t3OdqKw"
         },
         {
            "name":"駕到啦～",
            "url":"/media/sounds/.mp3_WVK2kgt"
         },
         {
            "name":"乾我屁事啊？",
            "url":"/media/sounds/.mp3_HkNRBpr"
         },
         {
            "name":"好康的呦～",
            "url":"/media/sounds/.mp3_4xdu00P"
         },
         {
            "name":"哎呀～比遊戲還刺激～",
            "url":"/media/sounds/.mp3_ygUHrD1"
         },
         {
            "name":"自慰行助理",
            "url":"/media/sounds/.mp3_GDLviK8"
         },
         {
            "name":"真香啊！",
            "url":"/media/sounds/.mp3_scKzIcl"
         },
         {
            "name":"小雞雞！",
            "url":"/media/sounds/.mp3_QD0ed1q"
         },
         {
            "name":"たのし～",
            "url":"/media/sounds/.mp3_5uTg6Ju"
         },
         {
            "name":"你好壞喔",
            "url":"/media/sounds/.mp3_Wmq5JOP"
         },
         {
            "name":"你這樣對嗎？",
            "url":"/media/sounds/.mp3_wTOuu4G"
         },
         {
            "name":"我要多穿兩條內褲",
            "url":"/media/sounds/.mp3_T2RwEiC"
         },
         {
            "name":"濕寶～",
            "url":"/media/sounds/.mp3_TlXemTV"
         },
         {
            "name":"猴塞雷啊",
            "url":"/media/sounds/.mp3_WqgyN9r"
         },
         {
            "name":"我把我動產不動產家屁眼全賣了",
            "url":"/media/sounds/.mp3_4EAgDOQ"
         },
         {
            "name":"兆元笑",
            "url":"/media/sounds/.mp3_HzEUCWM"
         },
         {
            "name":"我怎麼可能這麼做啊！",
            "url":"/media/sounds/.mp3_tEq1Kr4"
         },
         {
            "name":"我要幫你改運了喔",
            "url":"/media/sounds/.mp3_9VRSqMg"
         },
         {
            "name":"你醒啦",
            "url":"/media/sounds/.mp3_tQmi6hn"
         },
         {
            "name":"哎呦！你醒啦～",
            "url":"/media/sounds/.mp3_EqDC0c7"
         },
         {
            "name":"HappyBirthday",
            "url":"/media/sounds/happy-birthday_XLXSzYR.mp3"
         },
         {
            "name":"所有人都是我老婆",
            "url":"/media/sounds/.mp3_sbj994Y"
         },
         {
            "name":"怎麼變這麼婆這麼漂亮啊",
            "url":"/media/sounds/.mp3_bBgDhny"
         },
         {
            "name":"天地最強宇宙真理",
            "url":"/media/sounds/.mp3_pf1EKSO"
         },
         {
            "name":"臀部誘人的曲線",
            "url":"/media/sounds/.mp3_zd4cwBd"
         },
         {
            "name":"哎呀～我眼睛業障重啊～",
            "url":"/media/sounds/.mp3_FNsal5K"
         },
         {
            "name":"啊啊～好棒！",
            "url":"/media/sounds/.mp3_2Pf6ty4"
         },
         {
            "name":"幹太棒了吧！",
            "url":"/media/sounds/.mp3_9shXRMQ"
         },
         {
            "name":"放開我啊～",
            "url":"/media/sounds/.mp3_DkRpadZ"
         },
         {
            "name":"小孩子才做選擇",
            "url":"/media/sounds/.mp3_T2K3Tyu"
         },
         {
            "name":"我全要",
            "url":"/media/sounds/.mp3_tYxrJKZ"
         },
         {
            "name":"等一下好好去房間調教調教你",
            "url":"/media/sounds/.mp3_1zWRMoS"
         },
         {
            "name":"謀啦～",
            "url":"/media/sounds/.mp3_a3v7rwf"
         },
         {
            "name":"只不過是個",
            "url":"/media/sounds/.mp3_A6IHG8S"
         },
         {
            "name":"你知道",
            "url":"/media/sounds/.mp3_9lU2pXz"
         },
         {
            "name":"什麼叫做",
            "url":"/media/sounds/.mp3_5FA9OZX"
         },
         {
            "name":"我的",
            "url":"/media/sounds/.mp3_E4jgfeU"
         },
         {
            "name":"味道",
            "url":"/media/sounds/.mp3_y8SNd88"
         },
         {
            "name":"嗎",
            "url":"/media/sounds/.mp3_vqxkMtX"
         },
         {
            "name":"蛤？",
            "url":"/media/sounds/.mp3_o1rNToO"
         },
         {
            "name":"在皮一點我就讓你晚上知道",
            "url":"/media/sounds/.mp3_rtzPJja"
         },
         {
            "name":"是怎樣啊",
            "url":"/media/sounds/.mp3_zO8brI2"
         },
         {
            "name":"我是瘟神嗎？",
            "url":"/media/sounds/.mp3_uBnLvz5"
         },
         {
            "name":"桌子底下",
            "url":"/media/sounds/.mp3_CXt5AG7"
         },
         {
            "name":"起來一下",
            "url":"/media/sounds/.mp3_UNGUHko"
         },
         {
            "name":"叫你啊",
            "url":"/media/sounds/.mp3_ivKY1ab"
         },
         {
            "name":"好不好",
            "url":"/media/sounds/.mp3_zBn6ZhZ"
         },
         {
            "name":"什麼歌？",
            "url":"/media/sounds/.mp3_9Sx3Fi1"
         },
         {
            "name":"哪➚尼➚",
            "url":"/media/sounds/.mp3_NXAg8RW"
         },
         {
            "name":"這麼牛逼的嗎？",
            "url":"/media/sounds/.mp3_FYwiWr9"
         },
    ],
    '嘎抓': [
        {
            "name":"嘎抓打呼",
            "url":"/media/sounds/1_RxbUSue.mp3"
         },
         {
            "name":"嘎抓：幹你娘",
            "url":"/media/sounds/.mp3_GjxolX3"
         },
         {
            "name":"嘎抓：哭啊！",
            "url":"/media/sounds/.mp3_uTV0SgR"
         },
         {
            "name":"嘎抓：大濕不讓我睡",
            "url":"/media/sounds/.mp3_kF8jAih"
         },
         {
            "name":"嘎抓：晚上只好跟大濕睡",
            "url":"/media/sounds/.mp3_TkV8jZD"
         },
         {
            "name":"嘎抓：我是甲",
            "url":"/media/sounds/22_c7ccMHg.mp3"
         },
         {
            "name":"嘎抓：阿偉阿偉",
            "url":"/media/sounds/.mp3_wErZH4e"
         },
         {
            "name":"嘎抓：大濕屁眼會咬人",
            "url":"/media/sounds/.mp3_8DmmgHn"
         },
         {
            "name":"嘎抓：哇操",
            "url":"/media/sounds/.mp3_HYy5DzO"
         },
         {
            "name":"嘎抓：皮卡屁",
            "url":"/media/sounds/.mp3_J897yVm"
         },
         {
            "name":"嘎抓：不要在肛了",
            "url":"/media/sounds/.mp3_olO5X0N"
         },
         {
            "name":"嘎抓：輕一點",
            "url":"/media/sounds/.mp3_QnNGMFq"
         },
         {
            "name":"嘎抓：啊➚～",
            "url":"/media/sounds/.mp3_fkpe546"
         },
         {
            "name":"嘎抓：啊➚～～",
            "url":"/media/sounds/.mp3_bu8GFyv"
         },
         {
            "name":"嘎抓：『嘎抓不是會脫窗的人』",
            "url":"/media/sounds/.mp3_uA48kwL"
         },
         {
            "name":"嘎抓：『啊啊啊～』",
            "url":"/media/sounds/.mp3_GZFizCd"
         },
         {
            "name":"嘎抓：『睡到脫肛』",
            "url":"/media/sounds/.mp3_Nm0zWnN"
         },
         {
            "name":"嘎抓：『YA～』",
            "url":"/media/sounds/ya_wCoZNji.mp3"
         },
         {
            "name":"嘎抓：『好耶～』",
            "url":"/media/sounds/.mp3_13lV1ef"
         },
         {
            "name":"嘎抓：『我最喜歡睡覺了～』",
            "url":"/media/sounds/.mp3_cZF35G5"
         },
         {
            "name":"嘎抓：『大家好我是嘎抓』",
            "url":"/media/sounds/.mp3_DY0avBP"
         },
         {
            "name":"嘎抓：『好爛喔』",
            "url":"/media/sounds/.mp3_P5fcwfI"
         },
         {
            "name":"嘎抓：『什麼垃圾東西啊？』",
            "url":"/media/sounds/.mp3_3JCSP0p"
         },
         {
            "name":"嘎抓：『好想過去給你肛喔』",
            "url":"/media/sounds/.mp3_51pWKeR"
         },
         {
            "name":"嘎抓打哈欠",
            "url":"/media/sounds/.mp3_bad7QgK"
         },
         {
            "name":"嘎抓：『謝謝喔～』",
            "url":"/media/sounds/.mp3_SXTZPPk"
         },
         {
            "name":"嘎抓：『歡迎來我頻道訂閱我喔～YA～』",
            "url":"/media/sounds/ya_GtcXMc0.mp3"
         },
         {
            "name":"嘎抓：B_打開",
            "url":"/media/sounds/b_oyzGb08.mp3"
         },
         {
            "name":"嘎抓：『我講B_打開感覺好色』",
            "url":"/media/sounds/b_yA806v0.mp3"
         },
         {
            "name":"嘎抓：『感都是用肺換來的』",
            "url":"/media/sounds/.mp3_oObkOG5"
         },
         {
            "name":"嘎抓：『嗨大好我是小嘎』",
            "url":"/media/sounds/.mp3_AJZNYxW"
         },
         {
            "name":"嘎抓：『呱』",
            "url":"/media/sounds/.mp3_7CYURUm"
         },
         {
            "name":"嘎抓：『來跟妹子說早安嘍』",
            "url":"/media/sounds/.mp3_90yldZh"
         },
         {
            "name":"嘎抓：『給你吃點好吃的呦』",
            "url":"/media/sounds/.mp3_xrBlhwx"
         },
         {
            "name":"嘎抓：『ㄘ你ㄇㄉ』",
            "url":"/media/sounds/.mp3_AkIrk09"
         },
         {
            "name":"嘎抓：『皮皮』",
            "url":"/media/sounds/.mp3_Hrl5G1l"
         },
         {
            "name":"嘎抓：『我愛的人是皮卡屁』",
            "url":"/media/sounds/.mp3_Q8vbOIq"
         },
         {
            "name":"嘎抓出來了",
            "url":"/media/sounds/.mp3_lqERbh3"
         },
    ],
};